package com.miambiente.app.ui

import androidx.compose.runtime.Composable
import com.miambiente.app.ui.screens.*

/** Pantalla de un material: recibe solo la acción de volver. */
typealias Pantalla = @Composable (onVolver: () -> Unit) -> Unit

/**
 * Cada id del catálogo con su pantalla. `MainActivity` registra una ruta de
 * navegación por entrada, y una prueba unitaria verifica que ningún juego
 * del catálogo quede sin pantalla (antes eran ~90 `composable(...)`
 * escritos a mano, y olvidar uno hacía fallar la app al abrir ese juego).
 */
val PANTALLAS: Map<String, Pantalla> = mapOf(
    "formas" to { v -> FormasScreen(v) },
    "cuerpo" to { v -> CuerpoScreen(v) },
    "colores" to { v -> ColoresScreen(v) },
    "oficios" to { v -> OficiosScreen(v) },
    "torre-rosa" to { v -> TorreRosaScreen(v) },
    "dias-semana" to { v -> DiasSemanaScreen(v) },
    "estaciones" to { v -> EstacionesScreen(v) },
    "ciclo-vida" to { v -> CicloVidaScreen(v) },
    "seres-vivos" to { v -> SeresVivosScreen(v) },
    "habitat" to { v -> HabitatScreen(v) },
    "dieta-animal" to { v -> DietaAnimalScreen(v) },
    "fruta-verdura" to { v -> FrutaVerduraScreen(v) },
    "el-la" to { v -> ElLaScreen(v) },
    "pares-impares" to { v -> ParesImparesScreen(v) },
    "tamanos" to { v -> TamanosScreen(v) },
    "estados-agua" to { v -> EstadosAguaScreen(v) },
    "dia-noche" to { v -> DiaNocheScreen(v) },
    "singular-plural" to { v -> SingularPluralScreen(v) },
    "transporte" to { v -> TransporteScreen(v) },
    "pinza" to { v -> PinzaScreen(v) },
    "husos" to { v -> HusosScreen(v) },
    "contar" to { v -> ContarScreen(v) },
    "animales" to { v -> AnimalesScreen(v) },
    "solidos" to { v -> SolidosScreen(v) },
    "sentidos" to { v -> SentidosScreen(v) },
    "partes-planta" to { v -> PartesPlantaScreen(v) },
    "banderas" to { v -> BanderasScreen(v) },
    "sonidos-iniciales" to { v -> SonidosInicialesScreen(v) },
    "vocales" to { v -> VocalesScreen(v) },
    "abecedario" to { v -> AbecedarioScreen(v) },
    "ingles" to { v -> InglesScreen(v) },
    "emociones" to { v -> EmocionesScreen(v) },
    "tiempo" to { v -> TiempoScreen(v) },
    "reloj" to { v -> RelojScreen(v) },
    "sombras" to { v -> SombrasScreen(v) },
    "letras-lija" to { v -> LetrasLijaScreen(v) },
    "escalera-marron" to { v -> EscaleraMarronScreen(v) },
    "cilindros" to { v -> CilindrosScreen(v) },
    "sistema-solar" to { v -> SistemaSolarScreen(v) },
    "ciclo-agua" to { v -> CicloAguaScreen(v) },
    "rutina" to { v -> RutinaScreen(v) },
    "mesa" to { v -> MesaScreen(v) },
    "lavado-manos" to { v -> LavadoManosScreen(v) },
    "barras-numericas" to { v -> BarrasNumericasScreen(v) },
    "numeros" to { v -> NumerosScreen(v) },
    "textura" to { v -> TexturaScreen(v) },
    "temperatura" to { v -> TemperaturaScreen(v) },
    "peso" to { v -> PesoScreen(v) },
    "sabor" to { v -> SaborScreen(v) },
    "olfato" to { v -> OlfatoScreen(v) },
    "mayusculas" to { v -> MayusculasScreen(v) },
    "lados" to { v -> LadosScreen(v) },
    "mitades" to { v -> MitadesScreen(v) },
    "rimas" to { v -> RimasScreen(v) },
    "silabas" to { v -> SilabasScreen(v) },
    "continentes" to { v -> ContinentesScreen(v) },
    "tierra-agua" to { v -> TierraAguaScreen(v) },
    "orificios" to { v -> OrificiosScreen(v) },
    "vida-practica" to { v -> VidaPracticaScreen(v) },
    "gato" to { v -> GatoScreen(v) },
    "rps" to { v -> RpsScreen(v) },
    "memorama" to { v -> MemoramaScreen(v) },
    "que-falta" to { v -> QueFaltaScreen(v) },
    "diferencias" to { v -> DiferenciasScreen(v) },
    "objetos" to { v -> ObjetosScreen(v) },
    "memoria-turnos" to { v -> MemoriaTurnosScreen(v) },
    "patron" to { v -> PatronScreen(v) },
    "pizarra" to { v -> PizarraScreen(v) },
    "collage" to { v -> CollageScreen(v) },
    "colorear" to { v -> ColorearScreen(v) },
    "xilofono" to { v -> XilofonoScreen(v) },
    "mesa-silencio" to { v -> MesaSilencioScreen(v) },
    "cara" to { v -> CaraScreen(v) },
    "alfabeto-movil" to { v -> AlfabetoMovilScreen(v) },
    "trazos" to { v -> TrazosScreen(v) },
    "rompecabezas" to { v -> RompecabezasScreen(v) },
    "binomio" to { v -> BinomioScreen(v) },
    "tabla-cien" to { v -> TablaCienScreen(v) },
    "banco-dorado" to { v -> BancoDoradoScreen(v) },
    "domino" to { v -> DominoScreen(v) },
    "diez-objetos" to { v -> DiezObjetosScreen(v) },
    "diez-diferencias" to { v -> DiezDiferenciasScreen(v) },
    "laberinto" to { v -> LaberintoScreen(v) },
    "burbujas" to { v -> BurbujasScreen(v) },
    "canasta" to { v -> CanastaScreen(v) },
    "globo" to { v -> GloboScreen(v) },
    "arana" to { v -> AranaScreen(v) },
    "vibra-adivina" to { v -> VibraAdivinaScreen(v) },
    "reflejo-color" to { v -> ReflejoColorScreen(v) },
    "topo" to { v -> TopoScreen(v) },
    "snake" to { v -> SnakeScreen(v) },
    "tetris" to { v -> TetrisScreen(v) },
    "arkanoid" to { v -> ArkanoidScreen(v) },
    "palillos" to { v -> PalillosScreen(v) },
)
